#!/bin/zsh
# ================================================================================
# -- Author:        Michael Linder
# -- Company:       moosploit.com
# -- Project URL:   https://github.com/moosploit/auto-mac-setup
# -- License:       MIT License | http://www.opensource.org/licenses/MIT
# -- Description:   Some usefull additional bash functions
# ================================================================================
